[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://nmqkjrmuqslqgbhtjbkx.supabase.co"
  VITE_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_G4wm4s1L8-SaozRL64jk2w_geJL5MCs"
