-- Complete the instructor-managed sports dossier while keeping it under profile RLS.
alter table public.profiles
  add column if not exists internal_code text,
  add column if not exists enrollment_date date,
  add column if not exists sport_category text,
  add column if not exists modalities text[] not null default '{}',
  add column if not exists email text,
  add column if not exists address text,
  add column if not exists educational_institution text,
  add column if not exists course_year text,
  add column if not exists guardian_relationship text,
  add column if not exists guardian_email text,
  add column if not exists has_previous_taekwondo boolean,
  add column if not exists previous_club text,
  add column if not exists practice_duration text,
  add column if not exists other_sports text,
  add column if not exists last_competition text,
  add column if not exists last_competition_level text,
  add column if not exists training_observations text,
  add column if not exists performance_assessments jsonb not null default '{}'::jsonb,
  add column if not exists short_term_goal text,
  add column if not exists medium_term_goal text,
  add column if not exists long_term_goal text,
  add column if not exists training_focus text[] not null default '{}',
  add column if not exists competition_records jsonb not null default '[]'::jsonb,
  add column if not exists medals_summary text,
  add column if not exists grade_records jsonb not null default '[]'::jsonb,
  add column if not exists coach_strengths text,
  add column if not exists coach_improvements text,
  add column if not exists coach_recommendations text,
  add column if not exists athlete_stage text check (athlete_stage is null or athlete_stage in ('iniciacion', 'formacion', 'desarrollo', 'competicion', 'alto_rendimiento')),
  add column if not exists instructor_responsible text,
  add column if not exists instructor_record_date date,
  add column if not exists athlete_acknowledgement text,
  add column if not exists athlete_record_date date,
  add column if not exists guardian_acknowledgement text,
  add column if not exists guardian_record_date date;

grant update (internal_code, enrollment_date, sport_category, modalities, email, address,
  educational_institution, course_year, guardian_relationship, guardian_email,
  has_previous_taekwondo, previous_club, practice_duration, other_sports,
  last_competition, last_competition_level, training_observations,
  performance_assessments, short_term_goal, medium_term_goal, long_term_goal,
  training_focus, competition_records, medals_summary, grade_records,
  coach_strengths, coach_improvements, coach_recommendations, athlete_stage,
  instructor_responsible, instructor_record_date, athlete_acknowledgement,
  athlete_record_date, guardian_acknowledgement, guardian_record_date)
on public.profiles to authenticated;
